# Generated by Django 3.2.18 on 2023-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-05-27'),
            preserve_default=False,
        ),
    ]
